---
- name: Setup bonding
  block:
    - name: Setup config files for bond master interfaces
      community.general.nmcli:
        type: bond
        conn_name: "{{ interface.logicalname }}"
        ifname: "{{ interface.logicalname }}"
        gw4: >-
          {{ (interface.logicalname
              == network_manager_interfaces[0].logicalname)
             | ternary(network_manager_gateway, omit) }}
        mac: >-
          {{ interface.macaddress
          | default(network_manager_ip_mac_map[interface.ipv4.0.address]) }}
        ip4: >-
          {{ (interface.ipv4 | length > 1)
             | ternary( lookup('template', 'ip_list.j2') | from_yaml | list,
                      interface.ipv4.0.address
                      +"/"
                      + interface.ipv4.0.cidr ) }}
        method6: >-
          {{ (ansible_facts.distribution_major_version is version("8", "<"))
             | ternary("ignore", "disabled") }}
        routes4: "{{ lookup('template', 'routes.j2') | from_yaml | list }}"
        state: present
      loop: >-
        {{ network_manager_interfaces
           | selectattr("bond_options", "defined")
           | selectattr("bond_master", "undefined")
           | list }}
      loop_control:
        loop_var: interface
        label: "{{ interface.logicalname }}"
      notify:
        - reboot host
        - wait host

    - name: Setup config files for bond slave interfaces
      community.general.nmcli:
        type: bond-slave
        conn_name: "{{ interface.logicalname }}"
        ifname: "{{ interface.logicalname }}"
        master: "{{ interface.bond_master }}"
        state: present
      loop: >-
        {{ network_manager_interfaces
           | selectattr("bond_master", "defined")
           | list }}
      loop_control:
        loop_var: interface
        label: "{{ interface.logicalname }}"
      notify:
        - reboot host
        - wait host

    - name: Setup configuration file for bonding module
      ansible.builtin.template:
        src: bond_config.j2
        dest: "{{ network_manager_bonding_config_path }}"
        mode: 0755
      loop: >-
        {{ network_manager_interfaces
           | selectattr("bond_options", "defined")
           | selectattr("bond_master", "undefined")
           | list }}
      loop_control:
        loop_var: interface
        label: "{{ interface.logicalname }}"
  tags:
    - role::network_manager
    - role::network_manager::bonding
