---

- name: Setup dns config
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: "{{ network_manager_resolv_config_path }}"
    mode: 0644
  tags:
    - role::network_manager
    - role::network_manager::dns
