---
# Kernel modules tasks

- name: Setup kernel modules
  block:
    - ansible.builtin.include_tasks: kernel_modules_6.yml
      when: ansible_facts.distribution_major_version is version("6", "==")

    - ansible.builtin.include_tasks: kernel_modules_7.yml
      when: ansible_facts.distribution_major_version is version("7", ">=")
  tags:
    - role::network_interfaces
    - role::network_manager::kernel
