---

- name: Setup kernel
  block:
    - name: Setup 802.1q module
      ansible.builtin.copy:
        dest: /etc/modules-load.d/8021q.conf
        content: 8021q
        mode: 0644
      when: >-
        network_manager_interfaces
        | selectattr("vlanid", "defined")
        | list
        | length > 0

    - name: Setup bonding module
      ansible.builtin.copy:
        dest: /etc/modules-load.d/bonding.conf
        content: bonding
        mode: 0644
      when: >-
        network_manager_interfaces
        | selectattr("bond_master", "defined")
        | list
        | length > 0
  tags:
    - role::network_manager
    - role::network_manager::kernel
