---

- name: Setup network
  block:
    - name: Setup prerequisites
      ansible.builtin.include_tasks: prerequisites.yml

    - name: Setup facts
      ansible.builtin.include_tasks: facts.yml
      tags:
        - role::network_manager::facts

    - name: Cleanup
      ansible.builtin.include_tasks: cleanup.yml
      tags:
        - role::network_manager::cleanup

    - name: Setup ipv6
      ansible.builtin.include_tasks: ipv6.yml
      tags:
        - role::network_manager::ipv6

    - name: Setup hostname
      ansible.builtin.include_tasks: hostname.yml
      tags:
        - role::network_manager::hostname

    - name: Setup dns
      ansible.builtin.include_tasks: dns.yml
      tags:
        - role::network_manager::dns

    - name: Setup kernel
      ansible.builtin.include_tasks: kernel.yml
      tags:
        - role::network_manager::kernel

    - name: Setup udev
      ansible.builtin.include_tasks: udev.yml
      tags:
        - role::network_manager::udev

    - name: Setup interfaces
      ansible.builtin.include_tasks: interfaces.yml
      tags:
        - role::network_manager::interfaces

    - name: Setup vlans
      ansible.builtin.include_tasks: vlans.yml
      tags:
        - role::network_manager::interfaces
        - role::network_manager::vlans

    - name: Setup bonding
      ansible.builtin.include_tasks: bonding.yml
      tags:
        - role::network_manager::bonding

    - name: Setup mtu
      ansible.builtin.include_tasks: mtu.yml
      tags:
        - role::network_manager::mtu

    - name: Setup arp
      ansible.builtin.include_tasks: arp.yml
      tags:
        - role::network_manager::arp
  tags:
    - role::network_manager
