---

- name: Setup NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: yes
  tags:
    - role::network_manager
    - role::network_manager::service
