---

- name: Setup udev persistent net rules
  ansible.builtin.template:
    src: persistent_net_rules.j2
    dest: "{{ network_manager_udev_persistent_rules_path }}"
    mode: 0644
  notify:
    - reboot host
    - wait host
  tags:
    - role::network_manager
    - role::network_manager::udev
