---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Setup network device in /etc/modules-load.d
      ansible.builtin.copy:
        content: "e1000"
        dest: /etc/modules-load.d/e1000.conf
        mode: 0644
      when: ansible_facts.distribution_major_version is version("7", ">=")
